### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by Zuko**
All strings are translated but some of them didn't work... dunno why (eg. "Push to Talk Settings")

### CODE REVIEW

**Comment by acomminos** [comment]
Hi, you commented earlier saying that upstream FCs on connect? Are you still having this issue, or did you resolve it? If it's still a problem, a stack trace would be great.

Thanks.

**Comment by Zuko** [comment]
I just check this twice (build -> clean -> build), my test build always FC when connecting to server. (or just after)
[In my build I just translate strings]

http://syf.z.hlds.pl/log.txt 1,88 kB

btw. why some strings are always in English?

Edit. strings you can check on emulator - just set language to "polski"

**Comment by Zuko** [comment]
Log from "new" build and "new" emulator, android 4.1.2, language English - http://syf.z.hlds.pl/log2.txt 13,74 kB

**Comment by acomminos** [comment]
Please see if my latest commit fixes this issue for you. Thanks.

**Comment by Zuko** [comment]
On emulator and "real" device it's always stuck on "Synchronizing data with Mumble". Edit. after long, long time it's "fully" connected. 
Edit2. synchronization takes too long (~3min)

Log from "real" device - http://syf.z.hlds.pl/log3.txt 50,91 kB

**Pull request merged**
