### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by Zuko**
Translation for 1.7 RC1 is ready but:
- I need separate string "%s is now unmuted and undeafened". - I can't use same string for unmuted for "unmuted and undeafeaned" event in polish
- Where is disconnected message?

### CODE REVIEW

**Comment by acomminos** [comment]
Hi, not sure what you mean about the 'unmuted' string issue. Do you want the notifications 'unmuted and undeafened' to be split into two separate strings/messages?

BTW I forgot about the user disconnect message, I'll add that before 1.7.0 ships to the Play Store.

**Comment by Zuko** [comment]
I need another phrase for "unmuted and undeafened" event. 
I can't use same phrase for "unmuted" event and "unmuted and undeafened" event.

**Comment by acomminos** [comment]
Oh, ok- no problem. Will make those changes asap, going to merge these translations first.

**Comment by acomminos** [comment]
Added to latest commit.

**Pull request merged**
